[project]
name = 'Galactic-Dream-Collective-Hub'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.collective-problem-solving]
path = 'contracts/collective-problem-solving.clar'
clarity_version = 2
epoch = 2.5

[contracts.dream-sharing-session]
path = 'contracts/dream-sharing-session.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
